// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCz5rrN8HbrjZgsjzKGMbDfkTedgVLM-0',
    appId: '1:803921193676:web:a9d9a295f0e12883ec3069',
    messagingSenderId: '803921193676',
    projectId: 'hero-7cba3',
    authDomain: 'hero-7cba3.firebaseapp.com',
    databaseURL: 'https://hero-7cba3-default-rtdb.firebaseio.com',
    storageBucket: 'hero-7cba3.appspot.com',
    measurementId: 'G-WLY062WQEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGKRbd5izLq7nQxIkW6k-9NjGRfVQIJho',
    appId: '1:803921193676:android:d96d4ce7f8ac669fec3069',
    messagingSenderId: '803921193676',
    projectId: 'hero-7cba3',
    databaseURL: 'https://hero-7cba3-default-rtdb.firebaseio.com',
    storageBucket: 'hero-7cba3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCbW5MkywdvRdXSYFcstoN0e_IsZenIic',
    appId: '1:803921193676:ios:caafb141df6d02acec3069',
    messagingSenderId: '803921193676',
    projectId: 'hero-7cba3',
    databaseURL: 'https://hero-7cba3-default-rtdb.firebaseio.com',
    storageBucket: 'hero-7cba3.appspot.com',
    iosClientId: '803921193676-75trm4i6efn1r7486226fkjgo0c1f6h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.herovictoria02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCbW5MkywdvRdXSYFcstoN0e_IsZenIic',
    appId: '1:803921193676:ios:1274e226a6cbe161ec3069',
    messagingSenderId: '803921193676',
    projectId: 'hero-7cba3',
    databaseURL: 'https://hero-7cba3-default-rtdb.firebaseio.com',
    storageBucket: 'hero-7cba3.appspot.com',
    iosClientId: '803921193676-7hfn5tkjrdbohm42u2plnb2nd3nmkcgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.herovictoria02.RunnerTests',
  );
}
