name: herovictoria_02
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  camera: ^0.10.5+2
  path: ^1.6.2
  path_provider: ^2.0.15
  geolocator: ^8.2.1
  image_picker: ^1.0.2
  intl: ^0.17.0 # Librería intl
  timezone: ^0.7.0 # Librería horario
  cloud_firestore: 
  firebase_database:
  fluttertoast:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  http: any
  firebase_storage: ^11.2.6
  firebase_auth: ^4.0.1 #libreria para registrar, iniciar sesión y crear usuarios.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/